# sudo required for docker
sudo: true
dist: xenial

language: bash

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

# install qemu-user before running docker build
before_install:
  - |
    echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
    if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.md$)|(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)|^(docs)/'
    then
      echo "Only doc files were updated, not running the CI."
      exit
    fi
  - sudo docker run --privileged linuxkit/binfmt:v0.6
  - sudo docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform linux/armhf --oci-worker-platform linux/arm64
  - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
  - export BUILDKIT_HOST=tcp://0.0.0.0:1234

script:
  - bash ./travis/build.sh test-build

deploy:
  provider: script
  script: bash ./travis/build.sh latest
  skip_cleanup: true
  on:
    tags: true

# Don't email me the results of the test runs.
notifications:
  email: false
